### ISSUE TITLE
Thanks for this, do you know if it should work for DHT22? 

### ISSUE THREAD

**Issue by ljsweeny** [nilwes/DHT11#6]
I cannot install the DHTxx package, but this installs fine, however I get 0.00 values and some errors when trying it with DHT22. So I seem close, any suggestions? Would you expect it to work?

Thanks.

**Comment by floitsch** [comment]
This package doesn't support dht22.

Unless you are using toit v1 the dhtxx package is definitely what you want.
Feel free to file an issue there or join https://chat.toit.io. I would be happy to help you get it working.

**Comment by ljsweeny** [comment]
thanks, I'll figure how to install that.
